# mongodb-memory-server require node:24.0, not in alpine
FROM node:24.0 AS base 

WORKDIR /app

COPY package.json package-lock.json /app/

RUN npm install

FROM base AS final

COPY . .

EXPOSE 3000

CMD ["npx", "vitest", "--run", "--reporter", "verbose"]